### ISSUE TITLE
Seasons API Crash Report - NullPointerException in ChallengesTicker

### ISSUE THREAD

**Issue by eatnana** [kochkaev/seasons-api#3]
Seasons API Crash Report - NullPointerException in ChallengesTicker

Minecraft Version: 1.21.1
Seasons API Version: 1.2-BETA-2
Seasons Challenges Version: 1.0-RC-5
Fabric Loader Version: 0.16.9
Other Potentially Relevant Mods: Raid Restorer, Presents, Universal Perms, Floodgate (Bedrock player joined via Floodgate just before the crash).

Issue Description:

My server is experiencing crashes due to a NullPointerException originating within the ChallengesTicker class of the Seasons API. The crash occurs during a world tick, specifically within the removePlayersTask method (line 112 of ChallengesTicker.java). The error message indicates that a Map.get() call is returning null when it's expected to contain player data. This happened immediately after a Bedrock player, connected via Floodgate, disconnected from the server.

The crash occurred in the Nether dimension (minecraft:the_nether), but I haven't yet confirmed if it can be reproduced in other dimensions. I have observed a separate error earlier related to a permission check failing when this same Bedrock player joined, which might be related.

Crash Report:

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-11-15 22:32:58
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is null
	at knot//ru.kochkaev.api.seasons.ChallengesTicker.removePlayersTask(ChallengesTicker.java:112)
	at knot//ru.kochkaev.api.seasons.ChallengesTicker.tick(ChallengesTicker.java:78)
	at knot//net.minecraft.server.level.ServerLevel.handler$bki000$seasons-api$tick(ServerLevel.java:8314)
	at knot//net.minecraft.server.level.ServerLevel.tick(ServerLevel.java)
	at knot//net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1021)
	at knot//net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:299)
	at knot//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:912)
	at knot//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:281)
	at java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//ru.kochkaev.api.seasons.ChallengesTicker.removePlayersTask(ChallengesTicker.java:112)
	at knot//ru.kochkaev.api.seasons.ChallengesTicker.tick(ChallengesTicker.java:78)
	at knot//net.minecraft.class_3218.handler$bki000$seasons-api$tick(class_3218.java:8314)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 0
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (176,63,184), Section: (at 0,15,8 in 11,3,11; chunk contains blocks 176,0,176 to 191,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8680 game time, 8680 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: false
	Level weather: Rain time: 51227 (now: false), thunder time: 5633 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 0
Stacktrace:
	at knot//net.minecraft.class_3218.method_8538(class_3218.java:1693)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
	at knot//net.minecraft.class_3176.method_3813(class_3176.java:299)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows Server 2019 (amd64) version 10.0
	Java Version: 21.0.3, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3546324400 bytes (3382 MiB) / 4294967296 bytes (4096 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 7950X 16-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.49
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: Microsoft Basic Display Adapter
	Graphics card #0 vendor: Microsoft
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 10.0.17763.1
	Graphics card #1 name: Microsoft Basic Display Adapter
	Graphics card #1 vendor: Microsoft
	Graphics card #1 VRAM (MiB): 0.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 10.0.17763.1
	Graphics card #2 name: Microsoft Basic Display Adapter
	Graphics card #2 vendor: Microsoft
	Graphics card #2 VRAM (MiB): 0.00
	Graphics card #2 deviceId: VideoController3
	Graphics card #2 versionInfo: 10.0.17763.1
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: RAM
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 0.00
	Memory slot #1 type: RAM
	Virtual memory max (MiB): 24575.47
	Virtual memory used (MiB): 16250.68
	Swap memory total (MiB): 0.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 9388.53, total: 51198.00
	Space in storage for workdir (MiB): available: 9388.53, total: 51198.00
	JVM Flags: 2 total; -Xms4G -Xmx8G
	Fabric Mods: 
		additionalstructures: Additional Structures 5.0.1-fabric
		alternate-current: Alternate Current 1.9.0
		amplified_nether: Amplified Nether 1.2.5
		architectury: Architectury 13.0.8
		armortweaks: ArmorTweaks 2.0.3-1.21
		async: Async 0.1.0+rc5-1.21.1
			com_electronwill_night-config_core: core 3.8.1
			com_electronwill_night-config_toml: toml 3.8.1
		better-fabric-console: Better Fabric Console 1.2.0
			net_fabricmc_mapping-io: mapping-io 0.6.1
			org_fusesource_jansi_jansi: jansi 2.4.1
			org_jline_jline: jline 3.27.0
			org_jline_jline-terminal-jansi: jline-terminal-jansi 3.27.0
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		better_trials_loot: Better Trials Loot 1-v1.0.0
		betterconcreteconversion: Better Concrete Conversion 1.0.0
		betterdeserttemples: YUNG's Better Desert Temples 1.21.1-Fabric-4.1.2
		betterdungeons: YUNG's Better Dungeons 1.21.1-Fabric-5.1.2
		betterendisland: YUNG's Better End Island 1.21.1-Fabric-3.1.1
		betterfortresses: YUNG's Better Nether Fortresses 1.21.1-Fabric-3.1.2
		betterjungletemples: YUNG's Better Jungle Temples 1.21.1-Fabric-3.1.1
		bettermineshafts: YUNG's Better Mineshafts 1.21.1-Fabric-5.1.1
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.21.1-Fabric-4.1.1
		betterstrongholds: YUNG's Better Strongholds 1.21.1-Fabric-5.1.2
		betterwitchhuts: YUNG's Better Witch Huts 1.21.1-Fabric-4.1.1
		biggerbarrels: Bigger Barrels 1.1.0
		blades-temples: Blade's Temples. 1.0.1
		blanketeconomy: BlanketEconomy 1.4
		bldnsemiblade: Blade's Dungeons. 1.0.0
		bombsaway: BombsAway 1.0.0
		candywrapper: CandyWrapper 0.2.6
		careful-break: Example mod 1.2.0
		chronograph: Chronograph 1.0.0
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		coalexplosion: Coal Explosion 1.12.0
		code: betterweaponsmith 1.0
		cottages: Cottages 1.0.1
		craftable_enchanted_golden_apple: Craftable Enchanted Golden Apple 1.0.8
		creeperhealing: Creeper Healing 2.0.1-1.21+
		cristellib: Cristel Lib 1.2.8
			blue_endless_jankson: jankson 1.2.3
		deathcoordinates: Death Coordinates 1.0.0
		directionhud: DirectionHUD 1.7.4+1.21-1.21.1
		dungeons_arise: When Dungeons Arise 2.1.60
		dungeons_arise_seven_seas: When Dungeons Arise: Seven Seas 1.0.3
		expanded_ecosphere: Expanded Ecosphere 3.4.1
		fabric-api: Fabric API 0.108.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.3.0+8e331c5719
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.23+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fabricproxy-lite: FabricProxy Lite 2.9.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		fallingtree: FallingTree 1.21.1.2
		farmtweaks: FarmTweaks 1.1+1.21.1
		floodgate: Floodgate 2.2.4-SNAPSHOT
			aopalliance_aopalliance: aopalliance 1.0
			cloud: Cloud 2.0.0-beta.7
				fabric-permissions-api-v0: fabric-permissions-api 0.3.1
				io_leangen_geantyref_geantyref: geantyref 1.3.15
				org_incendo_cloud-brigadier: cloud-brigadier 2.0.0-beta.8
				org_incendo_cloud-core: cloud-core 2.0.0-rc.2
				org_incendo_cloud-minecraft-modded-common-fabric-repack_: cloud-minecraft-modded-common-fabric-repack 2.0.0-beta.7
				org_incendo_cloud-services: cloud-services 2.0.0-rc.2
			com_google_guava_failureaccess: failureaccess 1.0.1
			jakarta_inject_jakarta_inject-api: jakarta.inject-api 2.0.1
			javax_inject_javax_inject: javax.inject 1
			org_geysermc_cumulus_cumulus: cumulus 1.1.2
			org_geysermc_event_events: events 1.1-SNAPSHOT
			org_geysermc_geyser_common_unshaded: common 2.2.1-SNAPSHOT
			org_java-websocket_java-websocket: Java-WebSocket 1.5.2
			org_lanternpowered_lmbda: lmbda 2.0.0
		flowing_fluids: Flowing Fluids 0.2
		formations: Formations 1.0.2
		fuji: Fuji 2.4.0-release-35824e7849
			com_jayway_jsonpath_json-path: json-path 2.9.0
			net_luckperms_api: api 5.4
			org_quartz-scheduler_quartz: quartz 2.5.0-rc1
			placeholder-api: Placeholder API 2.4.1+1.21
			sgui: sgui 1.6.0+1.21
		funcys-wandering-trader: funcy's wandering trader 1.0.0
		funcysnetheritehorsearmor: funcysNetheriteHorseArmor 1.0.0
		glore: Glowing ores 1.4.0
		hurricane: Hurricane 2.1.0
			com_typesafe_config: config 1.4.2
		idmxd: I Died, My Xp Didn't 1.1.1-1.21.1
		interdimensional-map-markers: Interdimensional Map Markers 1.0.3
		java: Java HotSpot(TM) 64-Bit Server VM 21
		mendable_anvils: Mendable Anvils 1.2.2
		midnightlib: MidnightLib 1.6.3
		mighty-racing: Mighty Racing Mod fabric1.20.3-1.0.5
		minecraft: Minecraft 1.21.1
		monkeyconfig: Monkey Config 0.1.2+1.21
			com_electronwill_night-config_hocon: hocon 3.7.2
			com_electronwill_night-config_json: json 3.7.2
			com_electronwill_night-config_yaml: yaml 3.7.2
		mr_ore_deposits: Ore Deposits 1.1
		mr_villager_fillmyxp: AIO - Villager! Fill my XP 1.2
		nashiplogger: NashIpLogger 2.0
		nullscape: Nullscape 1.2.7
		oplock: OpLock 1.1.0+1.21
		oth3r-sit: Sit! 1.1.10+1.21-1.21.1
		pentamana: Pentamana 0.1.8
		player-finder: Player Finder 1.0.1+1.21
		polydex: Polydex 1.2.4+1.21.1
			player-data-api: Player Data API 0.6.0+1.21
			predicate-api: Predicate API 0.5.1+1.21
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
			sidebar-api: Sidebar API 0.5.0+1.21
		polymer-bundled: Polymer 0.9.18+1.21.1
			polymer-autohost: Polymer (Auto Host) 0.9.18+1.21.1
				io_netty_netty-codec-http: netty-codec-http 4.1.82
			polymer-blocks: Polymer (Textured Blocks) 0.9.18+1.21.1
			polymer-common: Polymer (Common) 0.9.18+1.21.1
				packet_tweaker: Packet Tweaker 0.5.5+1.21
			polymer-core: Polymer (Core) 0.9.18+1.21.1
				polymer-networking: Polymer (Networking) 0.9.18+1.21.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.9.18+1.21.1
			polymer-resource-pack: Polymer (Resource Pack) 0.9.18+1.21.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.9.18+1.21.1
		presents: Presents 1.0
		raid-restore: Raid Restorer 1.0.0
		redeemed: Redeemed 1.0.0
			com_mysql_mysql-connector-j: mysql-connector-j 8.2.0
			com_zaxxer_hikaricp: HikariCP 5.1.0
			org_mongodb_bson: bson 4.11.0
			org_mongodb_mongodb-driver-core: mongodb-driver-core 4.11.0
			org_mongodb_mongodb-driver-sync: mongodb-driver-sync 4.11.0
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.43.2.2
		rules4worlds: Rules4Worlds 0.1.0
		seasons-api: Seasons API 1.2-BETA-2
		seasons-challenges: Seasons Challenges 1.0-RC-5
		sepals: sepals 1.0.0
		servershop: ServerShop 1.5.0
		simpleconcrete: Simple Concrete 1.0-1.21.1
		skiesannouncements: SkiesAnnouncements 1.1.0-BETA2
			adventure-platform-fabric: adventure-platform-fabric 5.14.2
				net_kyori_adventure-api: adventure-api 4.17.0
				net_kyori_adventure-key: adventure-key 4.17.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.3
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.17.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.17.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.17.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.17.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.17.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.17.0
				net_kyori_ansi: ansi 1.1.0
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
				net_kyori_option: option 1.0.0
		skinrestorer: SkinRestorer 2.1.0+1.21-fabric
		skipservercheck: Frostbyte's Skip Server Movement Check 1.0.1
		skyvillages: Sky Villages 1.0.6
		splash_ominous: Splash Ominous 1.0.1
		sswaystones: sswaystones 1.1.3-HOTFIX
		stone-is-stone: Stone Is Stone 1.1.0+mc1.21.x
		structory: Structory 1.3.5
		structure_pool_api: Structure Pool API 1.1.3+1.21.1
		tbim: This boat is MINE! 1.0.1
		ticktweaks: Tick Tweaks 1.0.16-1.20.5-1.21.3
		time-lived: Time Lived 0.7.0+1.20.1
		trade: Trade 1.3+1.21
		treasuremap: TreasureMap 1.0.0
		u_framework: Unnamed Framework 1.0.2
		u_sea: Unnamed Sea 1.0.0
		underground_bunkers: Underground Bunkers 1.0.4
		universal_perms: Universal Perms 1.0.6
		vanillaconstructs: Vanilla Constructs 1.0.1
		vestigate: Vestigate 1.1.0
		warputils: WarpUtils 0.3.3
		worldedit: WorldEdit 7.3.7+6929-c6af3a3
		yungsapi: YUNG's API 1.21.1-Fabric-5.1.2
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		yungsbridges: YUNG's Bridges 1.21.1-Fabric-5.1.1
		yungsextras: YUNG's Extras 1.21.1-Fabric-5.1.1
	Server Running: true
	Player Count: 0 / 20; []
	Active Data Packs: vanilla, fabric, additionalstructures, amplified_nether (incompatible), better_trials_loot (incompatible), betterdeserttemples (incompatible), betterdungeons (incompatible), betterendisland (incompatible), betterfortresses (incompatible), betterjungletemples (incompatible), bettermineshafts (incompatible), betteroceanmonuments (incompatible), betterstrongholds (incompatible), betterwitchhuts (incompatible), blades-temples, bldnsemiblade, coalexplosion (incompatible), code, cottages, craftable_enchanted_golden_apple, dungeons_arise (incompatible), dungeons_arise_seven_seas, expanded_ecosphere, fabric-convention-tags-v2, mendable_anvils (incompatible), mr_ore_deposits, mr_villager_fillmyxp, nullscape, pentamana, polydex, seasons-api, server_translations_api, skyvillages, sswaystones, stone-is-stone, structory, u_framework, u_sea, underground_bunkers, vanillaconstructs, yungsbridges (incompatible), yungsextras (incompatible), expanded_ecosphere:resources/ee_default, expanded_ecosphere:resources/ee_remove_blobs
	Available Data Packs: additionalstructures, amplified_nether (incompatible), better_trials_loot (incompatible), betterdeserttemples (incompatible), betterdungeons (incompatible), betterendisland (incompatible), betterfortresses (incompatible), betterjungletemples (incompatible), bettermineshafts (incompatible), betteroceanmonuments (incompatible), betterstrongholds (incompatible), betterwitchhuts (incompatible), blades-temples, bldnsemiblade, bundle, coalexplosion (incompatible), code, cottages, craftable_enchanted_golden_apple, dungeons_arise (incompatible), dungeons_arise_seven_seas, expanded_ecosphere, expanded_ecosphere:resources/ee_default, expanded_ecosphere:resources/ee_remove_blobs, fabric, fabric-convention-tags-v2, mendable_anvils (incompatible), mr_ore_deposits, mr_villager_fillmyxp, nullscape, pentamana, polydex, seasons-api, server_translations_api, skyvillages, sswaystones, stone-is-stone, structory, trade_rebalance, u_framework, u_sea, underground_bunkers, vanilla, vanillaconstructs, yungsbridges (incompatible), yungsextras (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: -5994538373682349611
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
``` 

Additional Information:

I have checked for updates for all my mods, including Seasons API and Seasons Challenges, and I'm running the latest versions available.

I have tried temporarily disabling other mods that might interact with player data, but the crash persisted.

The server was running in offline mode.

I've attached the full crash report for your reference. Any assistance in diagnosing and resolving this issue would be greatly appreciated.

**Comment by kochkaev** [comment]
Thanks for the contribution, I will try to solve this problem as soon as possible.

**Comment by kochkaev** [comment]
Hi again, I tried to reproduce the error in myself but unfortunately I was unsuccessful. I have a few suggestions as to why this may be happening. Could you please share the weather during which the error occurs, as well as the Geyser and Floodgate configurations?
